### ISSUE TITLE
Neomodel objects + REST framework

### ISSUE THREAD

**Issue by ptchankue** [robinedwards/neomodel#150]
Hi there!
I would like to use neomodel to perform REST operations on a neo4j db. 
From the documentation I can create a model and save nodes in the database.

I tried to get all the nodes by doing a normal django get all: persons = Person.objects.all(), but neomodel doesn't support objects. This makes it difficult to write a serializer that will feed a REST framework.

Do you have a solution for this issue?

Regards,
Patrick

**Comment by theY4Kman** [comment]
Each `StructuredNode` subclass has a `nodes` object, which serves the same purpose as `objects` from Django's ORM. Some examples can be found in [the neomodel docs](http://neomodel.readthedocs.org/en/latest/queries.html). Here's another example for your case:

```python
from neomodel import StructuredNode, StringProperty

class Person(StructuredNode):
    name = StringProperty()

people = Person.nodes.all()
```

**Comment by bleib1dj** [comment]
@ptchankue expanding on @theY4Kman's answer I've used neomodel with the Django REST Framework utilizing something like `Person.nodes.all()` where you would normally use `Person.objects.all()` to access an object from the Django ORM. So you can quickly build a ViewSet by doing something along the lines of:

`views.py`
```
class PersonViewSet(viewsets.ModelViewSet):
    serializer_class = PersonSerializer
    lookup_field = "username"
    queryset = Person.nodes.all()

    def get_object(self):
        return Person.nodes.get(username=self.kwargs[self.lookup_field])
```

`serializers.py`
```
from rest_framework import serializers

class PlebSerializerNeo(serializers.Serializer):
    username = serializers.CharField()
```

If you are using an old version of DRF this may throw some errors due to it not using the core ORM but as of 3.1.2 which includes [PR #2745](https://github.com/tomchristie/django-rest-framework/pull/2754) those issues should be resolved.

**Comment by auvipy** [comment]
just curious, is drf serializer capable of serializing neomodels datatype?

**Comment by robinedwards** [comment]
I have never tried so I guess not but patches would be most welcome

**Comment by hustzoujia** [comment]
@bleib1dj 
thanks for your answers, but when i try this as your answer, some errors occured like this:
File "C:\Users\users\Desktop\venv_kg\lib\site-packages\rest_framework\routers.py", line 82, in register
    base_name = self.get_default_base_name(viewset)
  File "C:\Users\users\Desktop\venv_kg\lib\site-packages\rest_framework\routers.py", line 165, in get_default_base_name
    return queryset.model._meta.object_name.lower()
AttributeError: 'list' object has no attribute 'model'

en,  i think the reason is:   Person.nodes.all()   has no attribute 'model',  but i don't know how  to fix it.
could you help me to solve the problem,  thanks very much~！

**Comment by HashRocketSyntax** [comment]
I get stuck here in the serializer.

It looks like the attributes of the DjangoNode of django_neomodel (aka StructuredNode of neomodel) need to be altered in some way to mimic a regular model...

...so that it can work with this line of this code that is being used by the serializer of the model that you are abstracting...
opts = model._meta.concrete_model._meta

...from this file.
https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/model_meta.py

**Comment by Ramel** [comment]
Is there a way to summarize the use of neomodel + DRF with a Django demo app code?

**Comment by HashRocketSyntax** [comment]
@Ramel yes, in Python.

**Comment by Ramel** [comment]
I'm viewing here a lot of code pieces, and I cannot figure out the all picture to get it work. I assume you (@HashRocketSyntax) have write a custom serializer as you say in your update. But is there a way to document more your usage of DRF+Django? Is it different of this example: [paradise-paper-tutorial-serialize](https://neo4j-examples.github.io/paradise-papers-django/tutorial/part06.html#)?
