### ISSUE TITLE
Correction in section 3.9 "Extending neomodel" of documentation

### ISSUE THREAD

**Issue by siddharthm** [robinedwards/neomodel#157]
I believe there should be a correction in documentation of section 3.9. Currently the extend code is written as 
```python
class Person(StructuredNode):
    name = StringProperty(unique_index=True)
    def __init__(self, name, **args):
        self.name = name
        super(Person, self).__init__(self, **args)
```
while it should be 
```python
class Person(StructuredNode):
    name = StringProperty(unique_index=True)
    def __init__(self, name, *args, **kwargs):
        self.name = name
        super(Person, self).__init__(self, *args, **kwargs)
```
as the constructor of StructuredNode also takes in these 3 parameters

On a side note, I have a question whether something like selecting all nodes given a list is supported ( I cannot find it in current doc)? like the sql IN list query

**Comment by bleib1dj** [comment]
@siddharthm great thanks for the catch, if you wouldn't mind opening up a PR with that change I can get it merged in. If not I'll get it updated as soon as possible. 

For you side note there currently isn't a very clean way to accomplish that using one of neomodel's query methods. We can open up an additional ticket to investigate how something could be implemented to support it but in the mean time the easiest solution will probably to use a [cypher query](http://neomodel.readthedocs.org/en/latest/cypher.html). That will enable you to do something like the following:

```
from neomodel import db
query = "MATCH (tobias { name: 'Tobias' }),(others)" \
             "WHERE others.name IN ['Andres', 'Peter'] AND (tobias)<--(others)" \
             "RETURN others"
results, meta = db.cypher_query(query)
people = [Person.inflate(row[0]) for row in results]
```
Depending on what you want to accomplish the query could be changed to be something like
```
query = "MATCH (p:People) WHERE p.name IN ['Andres', 'Peter'] RETURN p"
```
There's a lot of documentation around `MATCH` queries [here](http://neo4j.com/docs/stable/query-where.html#where-filter-on-patterns) and specific docs on the `IN` usage for filtering [here](
http://neo4j.com/docs/stable/query-where.html#where-filter-on-patterns). 

Keep in mind that the class name you give to your model will be used to create a `Label` on the node that can be used to reduce the amount of nodes that are returned in your subgraph for filtering with `WHERE`. That's what the `People` reference in the second query is aimed at accomplishing rather than the first where it finds a node with an index of name but doesn't care about the type of node it's looking for.

**Comment by siddharthm** [comment]
@bleib1dj Thanks for the detailed and prompt reply. I have raised a pull request regarding the same https://github.com/robinedwards/neomodel/pull/158

Regarding second query i.e the in list query, I will try to provide a patch for the same soon

**Comment by bleib1dj** [comment]
@siddharthm, awesome thank you very much for the help :).
