### ISSUE TITLE
Generic Relationship

### ISSUE THREAD

**Issue by g3rd** [robinedwards/neomodel#206]
I am trying to create a generic relationship like where the To node can be any node defined:

```
( User ) --[ LIKES ]--> ( )
```

Thus in my StructuredNode class, do something like:

```
class User(StructuredNode):

    likes = RelationshipTo('*', 'LIKES')
```

Is this already supported and I just missed it in the docs / source?

Thoughts on a workaround? Or general approach for a PR?

Thanks!

**Comment by the4thv** [comment]
Hi @g3rd,

This isn't supported in Neomodel by default, because the first argument is the StructuredNode sub class name (e.g. 'User'). A workaround would be to extend the StructuredNode class to have a method that you can call that allows you to create a relationship to any StructuredNode object you pass in.

Kind Regards,

Dave
