### ISSUE TITLE
Django style connection settings

### ISSUE THREAD

**Issue by the4thv** [robinedwards/neomodel#219]
Hi @robinedwards, thank you so much for this!

In the work I did do, I wrote a new Database class in the utils that would support configuring the Neo4j settings like you might a RDBMS:
```
""" New format for the config parameters (Django):
        NEO4J_DATABASE = {
                'USER': '<username>',
                'PASSWORD': '<password>',
                'HOST': '<uri>',
                'PORT': '<port>',
                'BOLT': True|False,
                'SECURE': True|False
        }
"""
```
I can't remember how far I got with this, but would you be interested in using it?

[utils.zip](https://github.com/robinedwards/neomodel/files/614830/utils.zip)

**Comment by robinedwards** [comment]
Np :-) re the settings I think in core I am ok. But I think it would work
great in a django plugin. Which I think we should build.

**Comment by the4thv** [comment]
My plan was to support both calls in core and underlying remove passing username and password in the connection string and use Py2Neo's Graph() call with parameters instead. I make a branch, I'll move the django specific logic out into 'plugins/django.py' and keep the amendment connection call in core, ok?

**Comment by robinedwards** [comment]
Ah py2neo has been removed entirely it uses neo4j_driver internally. Re
django/plugins I was actually wanting to create a new python package
django_neomodel which handles all the django integration. I think the term
is a django 'app' in there lingo. Do you follow?

On 1 Dec 2016 10:17 a.m., "the4thv" <notifications@github.com> wrote:

My plan was to support both calls in core and underlying remove passing
username and password in the connection string and use Py2Neo's Graph()
call with parameters instead. I make a branch, I'll move the django
specific logic out into 'plugins/django.py' and keep the amendment
connection call in core, ok?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/robinedwards/neomodel/issues/219#issuecomment-264120824>,
or mute the thread

**Comment by the4thv** [comment]
Ah ok, no worries. I can work with that. Regarding the use of another python package for django, are you thinking of other functionality for django? Just going on my usage at the moment: neomodel is really good as it is and I wouldn't want to have to re-write anything in the models. If it's just the settings then I'm not sure it would justify an entire package itself?

**Comment by robinedwards** [comment]
Ah don't worry none of the API for neomodel would change.

The only thing that may move would be the signals integration. Initially it
may just be settings, some documentation and test integration but could
grow to include other things

**Comment by the4thv** [comment]
Hi Robin, is there a chance we chat a a skype chat on this? I really want to start coding on this, but I'm not sure how, for example, you would import neomodel into Django if we're using a 'django-neomodel' library as well as neomodel and how you envisage this working without making it so people need to refactor their code. I'll send you an email.

**Comment by robinedwards** [comment]
Hey not sure whether I can get to Skype but feel free to send me a email

**Comment by robinedwards** [comment]
@the4thv I've released the django plugin now https://github.com/robinedwards/django-neomodel so closing this issue.
