### ISSUE TITLE
Batch nodes operations get_or_create() with relationship property

### ISSUE THREAD

**Issue by alekgrom** [robinedwards/neomodel#249]
Can't get this example from [documentation](http://neomodel.readthedocs.io/en/latest/batch.html) to work.
The following error received:
'list' object has no attribute 'pets'

```
class Dog(StructuredNode):
    name = StringProperty(required=True)

    owner = RelationshipTo('Person', 'owner')

class Person(StructuredNode):
   name = StringProperty(unique_index=True)`

   pets = RelationshipFrom('Dog', 'owner')

bob = Person.get_or_create({"name": "Tom"})

bobs_gizmo = Dog.get_or_create({"name": "Gizmo"}, relationship=bob.pets)

tim = Person.get_or_create({"name": "Tim"})
tims_gizmo = Dog.get_or_create({"name": "Gizmo"}, relationship=tim.pets)

# not the same gizmo
assert bobs_gizmo[0] != tims_gismo[0]

```

**Comment by alekgrom** [comment]
The problem in this example could be fixed by changing:
`bob.pets` to `bob[0].pets`
`tim.pets` to `tim[0].pets`
But after change could be received the following error:
`"_rel_helper() got multiple values for argument 'lhs'"`

In this case should be modified the source code of "core.py" file:
`# line 381`
```
# TODO test this relationship parameter and document
query += _rel_helper('source', lhs=n_merge, ident=None,
                                 relation_type=relation_type, direction=OUTGOING)
```
Could be changed to:
```
query += _rel_helper(rhs='source', lhs=n_merge, ident=None,
                                 relation_type=relation_type, direction=OUTGOING)
```

**Comment by robinedwards** [comment]
Thanks for spotting this, I will apply this fix next week. Away at the
moment.

On 20 Apr 2017 12:31, "alekgrom" <notifications@github.com> wrote:

The problem in this example could be fixed by changing:
bob.pets to bob[0].pets
tim.pets to tim[0].pets
But after change could be received the following error:
"_rel_helper() got multiple values for argument 'lhs'"

In this case should be modified the source code of "core.py" file:
# line 381

# TODO test this relationship parameter and document
query += _rel_helper('source', lhs=n_merge, ident=None,
                                 relation_type=relation_type,
direction=OUTGOING)

Could be changed to:

query += _rel_helper(rhs='source', lhs=n_merge, ident=None,
                                 relation_type=relation_type,
direction=OUTGOING)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robinedwards/neomodel/issues/249#issuecomment-295674038>,
or mute the thread
